# Generated by Django 3.1.5 on 2021-01-31 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('count', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('manufactory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.manufactory', verbose_name='Manufactory')),
            ],
        ),
    ]
